#version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: soloapps_db
      MYSQL_USER: soloapps
      MYSQL_PASSWORD: soloapps
      MYSQL_ROOT_PASSWORD: soloapps
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    environment:
      - DB_HOST=mysql     # This should match the DB_HOST in the .env file
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - laravel_network

# Define volumes and networks
volumes:
  mysql_data:
    driver: local

networks:
  laravel_network:
    driver: bridge

