version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: soloapps_db
      MYSQL_USER: soloapps
      MYSQL_PASSWORD: soloapps
      MYSQL_ROOT_PASSWORD: soloapps
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psoloapps"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=soloapps_db
      - DB_USERNAME=soloapps
      - DB_PASSWORD=soloapps
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 120s

volumes:
  mysql_data:
    driver: local

networks:
  laravel_network:
    driver: bridge